mysql:
  user: root
  password: 123
  protocol: tcp
  host: localhost
  port: 3306
  db: bookstore

redis:
  host: localhost
  port: 6379
#  password: 123
  db: 0

frontend:
  booksPerPage: 20

session:
  lifetime: 86400
