mysql:
  user: root
  password: 123
  protocol: tcp
  host: localhost
  port: 3306
  db: bookstore

redis:
  host: localhost
  port: 6379
#  password: 123
  db: 0

mongo:
  host: localhost
  port: 27017
#  username: root
#  password: 123456

elasticsearch:
  host: localhost
  port: 9200
  username: elastic
  password: 123456
  cert: ./cert/http_ca.crt

frontend:
  booksPerPage: 20

session:
  lifetime: 86400
